name: MoveUI
main: adeynes\MoveUI\MoveUI
version: 1.0.0
api: 3.2.0
author: adeynes
description: The pinnacle of the brilliant masterminds @ PocketMine Discord
website: https://github.com/adeynes/MoveUI

commands:
  move:
    description: Displace thyself
    permission: moveui.move

permissions:
  moveui.move:
    default: true